CREATE TABLE `person` (
	`id` INT(10) NOT NULL,
	`name` INT(10) NOT NULL,
	`sex` INT(10) NOT NULL,
	`shower` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	`glasses` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	`hair` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	`boobs` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
