CREATE TABLE `people` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`sex` TINYINT(1) NOT NULL,
	`shower` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
	`glasses` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	`hair` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	`boobs` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
